[package]
name = "bara"
version = "0.1.0"
edition = "2021"

# [profile.release]
# strip = true
# lto = true

[dependencies]
chrono = { version="0.4.39", features = ["serde"] }
chrono-tz = "0.10.1"
uuid = { version = "1.13.1", features = ["v5"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0.138"
regex = "1.7"
pulldown-cmark = "0.13.0"
syntect = {version="5.2.0" }
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
walkdir = "2.5.0"
semver = "1.0"
clap = { version = "4.0", features = ["derive"] }
minijinja = { version="2.7.0", features=["loader"] }
grass = "0.13.4"
temp-dir = "0.1.14"
versions = "7.0.0"
two-face = { version = "0.4.3", features = ["syntect-default-onig"] }
futures = "0.3"
