name: Build

on:
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build artifact
        run: |
          cargo build --release