name: CI

on:
  push:
    branches: [trunk]

jobs:
  build:
    strategy:
      matrix:
        system: [x86_64-linux]
    runs-on: ${{ matrix.system == 'x86_64-linux' && 'ubuntu-latest' || 'macos-arm64' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Build for target system
        run: nix build .#devShells.${{ matrix.system }}

      - name: Lint and checks
        run: nix develop --command pre-commit run --all-files
